#!/bin/sh
#
# Wrapper script for the connmand daemon, mainly used to deal with
# the situation where we are booting via nfs
#

nfsroot=0
# if under nfsroot,  connmand does not handle any interface by default.
# if customer set the follow parameter, cannmand only handles it.
# example: EXTRA_PARAM="eth2,eth3"
# NOTE: customer setting maybe make nfsroot hang
EXTRA_PARAM=""

while read dev mtpt fstype rest; do
    if test "$mtpt" = "/"; then
	case $fstype in
	    nfs | nfs4)
		nfsroot=1
		break
		;;
	    *)
		;;
	esac
    fi
done < /proc/mounts

if test $nfsroot -eq 1; then
    if [ "$EXTRA_PARAM"x = ""x ]; then
        NET_DEVS=`cat /proc/net/dev | sed -ne 's/^\([a-zA-Z0-9 ]*\):.*$/\1/p'`
        EXTRA_PARAM="-I "
        for i in $NET_DEVS; do
            EXTRA_PARAM=$EXTRA_PARAM$i","
        done
    else
        EXTRA_PARAM="-i "$EXTRA_PARAM
    fi
    if [ "${EXTRA_PARAM: -1}"x = ","x ]; then
        EXTRA_PARAM=${EXTRA_PARAM%?}
    fi
fi

@SBINDIR@/connmand -n $EXTRA_PARAM
